# invoke it:
# ansible-playbook -i hosts.yml --ask-become-pass --become-user=$user develop.yml
# download applications from Github

# github_apps:
#   - { file: 'xh-v0.13.0-x86_64-unknown-linux-musl.tar.gz', repo_user: 'ducaale', repo_name: 'xh', version: 'v0.13.0' }
#   - { file: 'fzf-0.27.3-linux_amd64.tar.gz', repo_user: 'junegunn', repo_name: 'fzf', version: '0.27.3' }
#   - { file: 'fd-v8.2.1-x86_64-unknown-linux-musl.tar.gz', repo_user: 'sharkdp', repo_name: 'fd', version: 'v8.2.1' }
#   - { file: 'ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz ', repo_user: 'BurntSushi', repo_name: 'ripgrep', version: '13.0.0' }
#   - { file: 'dust-v0.7.5-x86_64-unknown-linux-musl.tar.gz', repo_user: 'bootandy', repo_name: 'dust', version: 'v0.7.5' }
#   - { file: 'task_linux_amd64.deb', repo_user: 'go-task', repo_name: 'task', version: 'v3.9.0' }
#   - { file: 'bat-v0.18.3-x86_64-unknown-linux-musl.tar.gz', repo_user: 'sharkdp', repo_name: 'bat', version: 'v0.18.3' }
#   - { file: 'starship-x86_64-unknown-linux-musl.tar.gz', repo_user: 'starship', repo_name: 'starship', version: 'v0.58.0' }

# - name: Creates directory
#   file:
#     path: "{{ ansible_env.HOME }}/github_apps"
#     state: directory

# - name: download api json of applications from Github
#   ansible.builtin.get_url:
#     url: "https://api.github.com/repos/{{ item.repo_user }}/{{ item.repo_name }}/releases/latest"
#     # url: "https://github.com/{{item.repo_user}}/{{ item.repo_name }}/releases/download/{{ item.version }}/{{ item.file }}"
#     force: yes
#     dest: "{{ ansible_env.HOME }}/github_apps/{{ item.repo_name }}.json"
#   loop: "{{ github_apps }}"

# - name: Get download url
#   shell: |
#     ls *.json | xargs jq '.assets | .[] | select(.browser_download_url | contains("x86_64-unknown-linux-musl.tar.gz")) | .browser_download_url' | sed -e 's/^"//' -e 's/"$// | xargs wget '

# - name: download files
#   shell: |
#     wget -i links.txt

