---
apt:
  # CLI
  git:
  vim:
  tmux:
  htop:
  curl:
  jq:
  tree:
  wget:
  p7zip:
  p7zip-full:
  snap:

  # Languages
  golang:
  nodejs:
  ruby:
  python3-pip:
  python3:

  # GUI
  vlc:
  wireshark-gtk:
  transmission-gtk:
  firefox:
  tor:
  gparted:
