- name: link dotfiles
  ansible.builtin.file:
    src: "{{ dot_files_repo_destination }}/src/{{ item.src }}"
    state: link
    path: "{{ansible_env.HOME}}/{{ item.dest }}"
    force: yes
  loop:
    - { src: ".bash_colors", dest: ".bash_colors" }
    - { src: ".bash_profile", dest: ".bash_profile" }
    - { src: ".bashrc", dest: ".bashrc" }
    - { src: ".gitconfig", dest: ".gitconfig" }
    - { src: ".inputrc", dest: ".inputrc" }
    - { src: ".tmux.conf", dest: ".tmux.conf" }
    - { src: ".vimrc ", dest: ".vimrc " }
    - { src: "vscode.settings.json", dest: ".config/Code/User/settings.json" }
